```{r}
library(tidyverse)
library(scales)
library(RColorBrewer)
library(arrow)
library(ggtext)
library(ggimage)

caption <- "Max Woolf — minimaxir.com"

sessionInfo()
```

```{r}
theme_set(theme_minimal(base_size = 8, base_family = "Overpass") +
  theme(
    plot.title = element_text(size = 8, face = "bold"),
    plot.subtitle = element_text(color = "#666666", size = 6),
    axis.title.x = element_text(size = 6),
    axis.title.y = element_text(size = 6),
    plot.caption = element_text(size = 5, color = "#969696"),
    plot.background = element_rect(fill = "#FFFFFF", color = "#FFFFFF"),
    legend.title = element_text(size = 8),
    # legend.key.width = unit(0.25, unit = "cm"),
    # panel.grid.minor = element_blank()
  ))
```

```{r}
gen_labels <- c(
  "Gen I" = 1,
  "Gen II" = 152,
  "Gen III" = 252,
  "Gen IV" = 387,
  "Gen V" = 494,
  "Gen VI" = 650,
  "Gen VII" = 722,
  "Gen VIII" = 810,
  "Gen IX" = 906,
  "Special" = 10001
)

print(names(gen_labels))
print(gen_labels)
```


```{r}
gen_bucket <- function(x) {
  gens <- cut(x, breaks = gen_labels, labels = names(gen_labels)[-length(gen_labels)], right=FALSE)

  # https://stackoverflow.com/a/39126746
  fct_na_value_to_level(gens, names(gen_labels)[length(gen_labels)])
}

gen_bucket(10000:10010)
```
```{r}
df_cosines <- read_parquet("pokemon_cossims.parquet") %>%
  mutate(gen_id_1 = gen_bucket(id_1), gen_id_2 = gen_bucket(id_2)) %>%
  mutate(id_1 = factor(id_1), id_2 = factor(id_2))

df_cosines %>% head()
```

```{r}
normalize_range <- function(x) {
  (x - min(x)) / (max(x) - min(x))
}

df_text_cossim <- df_cosines %>%
  filter(cossim_type == "text") %>%
  mutate(cossim_norm = normalize_range(cossim))
df_image_cossim <- df_cosines %>%
  filter(cossim_type == "image") %>%
  mutate(cossim_norm = normalize_range(cossim))
```



```{r}
plot <- ggplot(df_text_cossim, aes(x = id_1, y = id_2, fill = cossim)) +
  geom_raster(stat = "identity", interpolate = FALSE) +
  scale_x_discrete(breaks = gen_labels, labels = names(gen_labels)) +
  scale_y_discrete(breaks = gen_labels, labels = names(gen_labels)) +
  scale_fill_viridis_c(option = "viridis", end = 1.0) +
  labs(
    title = "Pokémon Similarity by Text Embedding of JSON Metadata",
    subtitle = "All Pokémon up to Scarlet/Violet DLC. \"Special\" includes Mega Evolutions, Formes, etc.", fill = "Cosine Similarity",
    caption = caption
  ) +
  theme(
    legend.position = "top",
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 5, margin = margin(c(0.05, 0.0, 0.0, 0.0), unit = "cm")),
    legend.key.width = unit(0.75, unit = "cm"),
    legend.key.height = unit(0.25, unit = "cm"),
    legend.margin = margin(c(0.0, 0.5, -0.2, 0.4), unit = "cm"),
    axis.text.x = element_text(size = 5, angle = 90, vjust = 0.5),
    axis.text.y = element_text(size = 5),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_line(linewidth = 0.5, color = "#969696")
    # axis.ticks.length.x = unit(., "cm"),
    # axis.ticks.length.y = unit(.25, "cm"),
  )

ggsave("pokemon_cossim_text.png", plot, width = 4, height = 4)
```

```{r}
plot <- ggplot(df_image_cossim, aes(x = id_1, y = id_2, fill = cossim)) +
  geom_raster(stat = "identity", interpolate = FALSE) +
  scale_x_discrete(breaks = gen_labels, labels = names(gen_labels)) +
  scale_y_discrete(breaks = gen_labels, labels = names(gen_labels)) +
  # scale_fill_viridis_c(option = "inferno", end = 0.8, limits = c(0.8, 1.0), na.value="#FFF") +
  scale_fill_viridis_c(option = "inferno", end = 1.0) +
  labs(
    title = "Pokémon Similarity by Image Embedding of JSON Metadata",
    subtitle = "All Pokémon up to Scarlet/Violet DLC. \"Special\" includes Mega Evolutions, Formes, etc.", fill = "Cosine Similarity",
    caption = caption
  ) +
  theme(
    legend.position = "top",
    legend.title = element_text(size = 6),
    legend.text = element_text(size = 5, margin = margin(c(0.05, 0.0, 0.0, 0.0), unit = "cm")),
    legend.key.width = unit(0.75, unit = "cm"),
    legend.key.height = unit(0.25, unit = "cm"),
    legend.margin = margin(c(0.0, 0.5, -0.2, 0.4), unit = "cm"),
    axis.text.x = element_text(size = 5, angle = 90, vjust = 0.5),
    axis.text.y = element_text(size = 5),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_line(linewidth = 0.5, color = "#969696")
    # axis.ticks.length.x = unit(., "cm"),
    # axis.ticks.length.y = unit(.25, "cm"),
  )

ggsave("pokemon_cossim_image.png", plot, width = 4, height = 4)
```


## Most Similar Pokemon By Each Generaton

```{r}
df_pokemon <- read_csv("pokemon.csv") %>%
  mutate(name = str_to_title(name)) %>%
  select(id, name)

df_pokemon %>% head()
```

```{r}
target_pokemon_id <- 25

df_subset <- df_text_cossim %>%
  filter(id_1 == target_pokemon_id, gen_id_2 != "Special") %>%
  group_by(gen_id_2) %>%
  slice_max(order_by = cossim, n = 3) %>%
  mutate(id_2 = as.numeric(levels(id_2))[id_2]) %>%
  left_join(df_pokemon, by=c("id_2" = "id")) %>%
  mutate(name = factor(name, levels=rev(name)))

df_subset
```

```{r}
plot <- ggplot(df_subset, aes(x = name, y = cossim, fill = gen_id_2)) +
  geom_bar(stat="identity") +
  geom_image(
    aes(image = sprintf("pokemon_images.nosync/%s.png", id_2), y=0),
    size = 0.30,
    nudge_y = 0.05
  ) +
  geom_text(aes(label = sprintf("%.3f", cossim)), family="Overpass", color="white", size=2, hjust=1.25) +
  scale_x_discrete() +
  scale_y_continuous(breaks = c(0.5, 1.0), limits=c(0.0, 1.0)) +
  coord_flip() +
  scale_fill_discrete(l=40, guide = NULL) +
  labs(
    title = "Cosine Similarities of a Pikachu Text Embedding vs. all Pokémon Embeddings",
    subtitle = "All Pokémon up to Scarlet/Violet DLC.",
    caption = caption
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
  ) +
  facet_wrap(vars(gen_id_2), nrow=3, scales="free_y")

ggsave("pikachu_similar_text.png", plot, width = 5, height = 3)
```

```{r}
df_subset <- df_image_cossim %>%
  filter(id_1 == target_pokemon_id, gen_id_2 != "Special") %>%
  group_by(gen_id_2) %>%
  slice_max(order_by = cossim, n = 3) %>%
  mutate(id_2 = as.numeric(levels(id_2))[id_2]) %>%
  left_join(df_pokemon, by=c("id_2" = "id")) %>%
  mutate(name = factor(name, levels=rev(name)))

df_subset
```

```{r}
plot <- ggplot(df_subset, aes(x = name, y = cossim, fill = gen_id_2)) +
  geom_bar(stat="identity") +
  geom_image(
    aes(image = sprintf("pokemon_images.nosync/%s.png", id_2), y=0),
    size = 0.30,
    nudge_y = 0.05
  ) +
  geom_text(aes(label = sprintf("%.3f", cossim)), family="Overpass", color="white", size=2, hjust=1.25) +
  scale_x_discrete() +
  scale_y_continuous(breaks = c(0.5, 1.0), limits=c(0.0, 1.0)) +
  coord_flip() +
  scale_fill_discrete(l=40, guide = NULL) +
  labs(
    title = "Cosine Similarities of a Pikachu Image Embedding vs. all Pokémon",
    subtitle = "All Pokémon up to Scarlet/Violet DLC.",
    caption = caption
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
  ) +
  facet_wrap(vars(gen_id_2), nrow=3, scales="free_y")

ggsave("pikachu_similar_image.png", plot, width = 5, height = 3)
```

Now that there is a working version with Pikachu, create a function so that it can be run in a loop.

```{r}
pokemon_similar <- function(target_pokemon_id) {
  df_subset <- df_text_cossim %>%
    filter(id_1 == target_pokemon_id, gen_id_2 != "Special") %>%
    group_by(gen_id_2) %>%
    slice_max(order_by = cossim, n = 3) %>%
    mutate(id_2 = as.numeric(levels(id_2))[id_2]) %>%
    left_join(df_pokemon, by=c("id_2" = "id")) %>%
    mutate(name = factor(name, levels=rev(name)))

  plot <- ggplot(df_subset, aes(x = name, y = cossim, fill = gen_id_2)) +
    geom_bar(stat="identity") +
    geom_image(
      aes(image = sprintf("pokemon_images.nosync/%s.png", id_2), y=0),
      size = 0.30,
      nudge_y = 0.05
    ) +
    geom_text(aes(label = sprintf("%.3f", cossim)), family="Overpass", color="white", size=2, hjust=1.25) +
    scale_x_discrete() +
    scale_y_continuous(breaks = c(0.5, 1.0), limits=c(0.0, 1.0)) +
    coord_flip() +
    scale_fill_discrete(l=40, guide = NULL) +
    labs(
      title = "Cosine Similarities of a Pikachu Text Embedding vs. all Pokémon",
      subtitle = "All Pokémon up to Scarlet/Violet DLC. \"Special\" includes Mega Evolutions, Formes, etc.",
      caption = caption
    ) +
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
    ) +
    facet_wrap(vars(gen_id_2), nrow=3, scales="free_y")

  ggsave(sprintf("%s_similar_image.png", target_pokemon_id), plot, width = 5, height = 3)
}
```

## Most Dissimilar Pokemon by Lowest Median Similarity

```{r}
df_dissimilar <- df_text_cossim %>%
  filter(gen_id_1 != "Special") %>%
  group_by(id_1, gen_id_1) %>%
  summarize(med_cossim = median(cossim)) %>%
  ungroup() %>%
  group_by(gen_id_1) %>%
  slice_min(order_by = med_cossim, n = 3) %>%
  mutate(id_1 = as.numeric(levels(id_1))[id_1]) %>%
  left_join(df_pokemon, by=c("id_1" = "id")) %>%
  mutate(name = factor(name, levels=rev(name)))

df_dissimilar %>% head()
```

```{r}
plot <- ggplot(df_dissimilar, aes(x = name, y = med_cossim, fill = gen_id_1)) +
  geom_bar(stat="identity") +
  geom_image(
    aes(image = sprintf("pokemon_images.nosync/%s.png", id_1), y=0),
    size = 0.30,
    nudge_y = 0.05
  ) +
  geom_text(aes(label = sprintf("%.3f", med_cossim)), family="Overpass", color="white", size=2, hjust=1.25) +
  scale_x_discrete() +
  scale_y_continuous(breaks = c(0.5, 1.0), limits=c(0.0, 1.0)) +
  coord_flip() +
  scale_fill_discrete(l=40, guide = NULL) +
  labs(
    title = "Pokémon With Lowest Median Cosine Similarity vs. All Other Pokémon, by Generation",
    subtitle = "All Pokémon up to Scarlet/Violet DLC.",
    caption = caption
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
  ) +
  facet_wrap(vars(gen_id_1), nrow=3, scales="free_y")

ggsave("pokemon_dissimilar_text.png", plot, width = 5, height = 3)
```