query rawPokemonData {
  pokemon_v2_pokemon(limit: 10, order_by: { id: asc }) {
    height
    base_experience
    name
    id
    pokemon_v2_pokemonabilities(
      distinct_on: ability_id
      order_by: { ability_id: asc }
    ) {
      pokemon_v2_ability {
        name
      }
    }
    pokemon_v2_pokemonmoves(distinct_on: move_id, order_by: { move_id: asc }) {
      pokemon_v2_move {
        name
        pokemon_v2_type {
          name
        }
      }
      pokemon_v2_movelearnmethod {
        name
      }
    }
    pokemon_v2_pokemonstats {
      pokemon_v2_stat {
        name
      }
      base_stat
      effort
    }
    weight
    pokemon_v2_encounters(
      distinct_on: location_area_id
      order_by: { location_area_id: asc }
    ) {
      id
      pokemon_v2_locationarea {
        pokemon_v2_location {
          name
          pokemon_v2_region {
            name
          }
        }
      }
    }
    pokemon_v2_pokemonspecy {
      base_happiness
      capture_rate
      evolves_from_species_id
      forms_switchable
      gender_rate
      has_gender_differences
      hatch_counter
      is_baby
      is_legendary
      is_mythical
      pokemon_v2_pokemonspeciesflavortexts(
        order_by: { id: asc }
        where: { language_id: { _eq: 9 } }
      ) {
        pokemon_v2_version {
          name
        }
        flavor_text
      }
      pokemon_v2_pokemonshape {
        name
      }
      pokemon_v2_pokemonhabitat {
        name
      }
      pokemon_v2_pokemonegggroups {
        pokemon_v2_egggroup {
          name
        }
      }
      pokemon_v2_generation {
        name
      }
      pokemon_v2_growthrate {
        name
      }
      pokemon_v2_pokemoncolor {
        name
      }
      pokemon_v2_pokemonevolutions {
        pokemon_v2_evolutiontrigger {
          name
        }
      }
    }
    pokemon_v2_pokemontypes(order_by: { id: asc }) {
      pokemon_v2_type {
        name
      }
    }
  }
}
